// Shared logic for @sauravvarma/catalyst-cloudflare: reads the app's opt-in config
// (the `catalystCloudflare` key in package.json) and generates the two files that used
// to be hand-copied from the README, worker/index.js and wrangler.jsonc, from templates
// that live inside this package. Because the package owns the templates, an adapter
// upgrade (e.g. a changed alias or compat flag) propagates on `npm update` + rebuild
// instead of leaving a stale hand-copied snapshot in the app.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"

export const ADAPTER = "@sauravvarma/catalyst-cloudflare"

// The 3 scripts `init` injects into the app's package.json.
export const SCRIPTS = {
    "build:worker": `node node_modules/${ADAPTER}/prebuild.mjs`,
    "dev:worker": "npm run build && npm run build:worker && wrangler dev",
    "deploy:worker": "npm run build && npm run build:worker && wrangler deploy",
}

// Turn an npm package name into a valid Workers service name (lowercase, dashes, no scope).
export function slugify(name) {
    return (
        String(name || "")
            .replace(/^@[^/]+\//, "")
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-")
            .replace(/^-+|-+$/g, "") || "catalyst-app"
    )
}

// Resolve the adapter config from the app's package.json. The only genuinely per-app
// value is the worker `name`; everything else has a safe default.
export function loadConfig(root) {
    const pkgPath = join(root, "package.json")
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
    const cc = pkg.catalystCloudflare || {}
    return {
        name: cc.name || slugify(pkg.name),
        // Routes that must always hit the Worker (SSR/API). Hashed assets under /assets/
        // are served by Workers Assets first; unmatched paths fall through to the Worker.
        routes: Array.isArray(cc.routes) && cc.routes.length ? cc.routes : ["/"],
        // Shallow-merged into the generated wrangler.jsonc so custom bindings (KV, D1,
        // vars, ...) are reachable without hand-editing a generated file.
        wrangler: cc.wrangler && typeof cc.wrangler === "object" ? cc.wrangler : {},
        pkg,
        pkgPath,
    }
}

// The Worker entry. It is byte-identical across apps but must be written into the app's
// own worker/ dir so its relative imports resolve against the app's build output.
export const WORKER_ENTRY = `// AUTO-GENERATED by ${ADAPTER} — do not edit.
// Regenerated on every \`npm run build:worker\`; change settings via the
// "catalystCloudflare" key in package.json instead.
import { createWorker } from "${ADAPTER}/worker/runtime"
import fsAssets from "./fs-assets.generated.js"
import app from "../build/expressServer.js"

export default createWorker(app, { fsAssets })
`

// Runtime env the Catalyst server reads via process.env. PUBLIC_STATIC_ASSET_URL is ""
// so SSR builds same-origin /assets/... URLs; it lives here (define + vars) rather than
// in the app's shared config/config.json, which the Node/container target also uses.
const ENV = {
    NODE_ENV: "production",
    IS_DEV_COMMAND: "false",
    src_path: "/",
    BUILD_OUTPUT_PATH: "build",
    PUBLIC_STATIC_ASSET_PATH: "/assets/",
    PUBLIC_STATIC_ASSET_URL: "",
}

const shim = (file) => `${ADAPTER}/worker/${file}`

const OTEL = [
    "api",
    "auto-instrumentations-node",
    "exporter-metrics-otlp-grpc",
    "exporter-metrics-otlp-http",
    "exporter-trace-otlp-grpc",
    "exporter-trace-otlp-http",
    "resources",
    "sdk-metrics",
    "sdk-node",
    "sdk-trace-node",
    "semantic-conventions",
]

// Deep-ish merge: top-level keys from `extra` win, but plain-object blocks (assets, vars,
// alias, define, ...) merge one level so a passthrough can add a single var/binding
// without discarding the generated block.
function mergeWrangler(base, extra) {
    const out = { ...base }
    for (const [k, v] of Object.entries(extra)) {
        const isObj = (x) => x && typeof x === "object" && !Array.isArray(x)
        out[k] = isObj(v) && isObj(out[k]) ? { ...out[k], ...v } : v
    }
    return out
}

export function buildWranglerConfig({ name, routes, wrangler }) {
    const define = { __dirname: '"/"', __filename: '"/worker/index.js"' }
    for (const [k, v] of Object.entries(ENV)) define[`process.env.${k}`] = JSON.stringify(v)

    const alias = {
        // The 3 @catalyst/* specifiers the built app requires -> compiled build/ output
        // (wrangler alias is exact-match; module-alias's require hook doesn't run here).
        "@catalyst/server/renderer": "./build/renderer/index.js",
        "@catalyst/server/utils/validator": "./build/utils/validator.js",
        "@catalyst/template/server/server.js": "./build/server.js",
        // Adapter shims.
        "react-dom/server": shim("react-dom-server-shim.js"),
        fs: shim("fs-shim.js"),
        "body-parser": shim("body-parser-stub.js"),
        compression: shim("middleware-factory-stub.js"),
        "express-static-gzip": shim("middleware-factory-stub.js"),
        tty: shim("tty-stub.js"),
        "node:tty": shim("tty-stub.js"),
    }
    for (const m of OTEL) alias[`@opentelemetry/${m}`] = shim("empty-stub.js")

    const base = {
        name,
        main: "worker/index.js",
        compatibility_date: "2025-09-01",
        compatibility_flags: ["nodejs_compat"],
        // Self service binding: lets server-side same-origin fetches dispatch to this
        // Worker's own routes in-process (see worker/runtime.js).
        services: [{ binding: "SELF", service: name }],
        assets: {
            directory: "./dist/public",
            not_found_handling: "none",
            run_worker_first: routes,
        },
        alias,
        define,
        vars: { ...ENV },
    }
    return mergeWrangler(base, wrangler)
}

// Write the two generated files into the app root. Returns the resolved config.
export function generate(root) {
    const cfg = loadConfig(root)
    const workerDir = join(root, "worker")
    mkdirSync(workerDir, { recursive: true })
    writeFileSync(join(workerDir, "index.js"), WORKER_ENTRY)
    writeFileSync(
        join(root, "wrangler.jsonc"),
        `// AUTO-GENERATED by ${ADAPTER} — do not edit.\n` +
            `// Change settings via the "catalystCloudflare" key in package.json, then rebuild.\n` +
            JSON.stringify(buildWranglerConfig(cfg), null, 4) +
            "\n",
    )
    return cfg
}
