// Worker entry: run the Catalyst production Express app natively on the Workers runtime.
// The @sauravvarma/catalyst-cloudflare runtime is imported first (installs the logger shim + fetch
// reroute) before the app module initializes.
import { createWorker } from "@sauravvarma/catalyst-cloudflare/worker/runtime"
import fsAssets from "./fs-assets.generated.js" // generated by the adapter prebuild
import app from "../build/expressServer.js" // @catalyst/* aliases resolved by wrangler

export default createWorker(app, { fsAssets })
