// catalyst-cloudflare prebuild — run from the Catalyst app root AFTER `catalyst build`.
// Prepares everything wrangler needs to bundle the Worker:
//   1. copies server/data -> build/data (babel doesn't copy non-JS server assets);
//   2. stages build/public -> dist/public/assets (+ SW/offline/favicon at root) for Workers Assets;
//   3. generates worker/fs-assets.generated.js (the map the fs-shim serves at request time).
import {
    readFileSync,
    writeFileSync,
    readdirSync,
    rmSync,
    mkdirSync,
    cpSync,
    existsSync,
    statSync,
} from "node:fs"
import { join } from "node:path"

const ROOT = process.cwd()
const BUILD_PUBLIC = join(ROOT, "build", "public")

if (!existsSync(BUILD_PUBLIC)) {
    console.error("catalyst-cloudflare prebuild: build/public not found — run `catalyst build` first.")
    process.exit(1)
}

// 1. server/data -> build/data
if (existsSync(join(ROOT, "server", "data"))) {
    cpSync(join(ROOT, "server", "data"), join(ROOT, "build", "data"), { recursive: true })
}

// 2. stage assets
const DIST_PUBLIC = join(ROOT, "dist", "public")
rmSync(DIST_PUBLIC, { recursive: true, force: true })
mkdirSync(join(DIST_PUBLIC, "assets"), { recursive: true })
cpSync(BUILD_PUBLIC, join(DIST_PUBLIC, "assets"), { recursive: true })
for (const f of ["catalyst-sw.js", "offline.html", "catalyst-offline-manifest.json"]) {
    const src = join(BUILD_PUBLIC, f)
    if (existsSync(src)) cpSync(src, join(DIST_PUBLIC, f))
}
if (existsSync(join(ROOT, "public", "favicon.ico"))) {
    cpSync(join(ROOT, "public", "favicon.ico"), join(DIST_PUBLIC, "favicon.ico"))
}

// 3. generate fs-assets map (loadable-stats.json + *.css, keyed by basename)
const map = {}
for (const f of readdirSync(BUILD_PUBLIC)) {
    const full = join(BUILD_PUBLIC, f)
    if (statSync(full).isFile() && /\.(json|css)$/.test(f)) {
        map[f] = readFileSync(full, "utf-8")
    }
}
mkdirSync(join(ROOT, "worker"), { recursive: true })
writeFileSync(
    join(ROOT, "worker", "fs-assets.generated.js"),
    `// AUTO-GENERATED by catalyst-cloudflare prebuild — do not edit.\nexport default ${JSON.stringify(map)}\n`,
)

console.log(
    `catalyst-cloudflare prebuild: staged ${readdirSync(join(DIST_PUBLIC, "assets")).length} assets, embedded ${Object.keys(map).length} fs files`,
)
